import "./globals.css";
import { Inter } from "next/font/google";

//components
import Allservices from "../components/Allservice";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tap Taxi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-auto container {inter.className} bg-slate-700">
        <h1 className="text-center text-white text-4xl p-4">This is Header</h1>
        <Allservices />
        {children}
        <h1 className="text-center text-white text-4xl p-4">This is Footer</h1>
      </body>
    </html>
  );
}
